# Generated by Django 3.2.5 on 2021-10-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.TextField(blank=True, null=True)),
                ('artist_main_genre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'artist_playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'artist_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreBig',
            fields=[
                ('genre_big_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_big_code', models.TextField(blank=True, null=True)),
                ('genre_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genre_big',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreBigSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'genre_big_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreDetail',
            fields=[
                ('genre_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_detail_code', models.TextField(blank=True, null=True)),
                ('genre_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genre_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreDetailSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'genre_detail_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('playlist_title', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlist',
                'ordering': ['-like_cnt'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'playlist_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'playlist_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.TextField(blank=True, null=True)),
                ('album_name', models.TextField(blank=True, null=True)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('song_name', models.TextField(blank=True, null=True)),
                ('added_cnt', models.IntegerField(blank=True, null=True)),
                ('thumb_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecentSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.TextField()),
                ('artist_main_genre', models.TextField()),
                ('artist_id', models.IntegerField()),
                ('song_id', models.IntegerField()),
                ('song_name', models.TextField()),
                ('cnt', models.IntegerField()),
                ('genre_big_name', models.TextField()),
                ('thunmb_url', models.TextField()),
            ],
        ),
    ]
